#include "token.hpp"
#include <string>

std::string phos::lex::token_to_string(phos::lex::TokenType t)
{
    switch(t) {
        case TokenType::Integer64:    return "Integer64";
        case TokenType::Float64:      return "Float64";
        case TokenType::String:       return "String";
        case TokenType::Bool:         return "Bool";
        case TokenType::Nil:          return "Nil";
        case TokenType::Identifier:   return "Identifier";
        case TokenType::TInt64:       return "TInt64";
        case TokenType::TInt32:       return "TInt32";
        case TokenType::TInt16:       return "TInt16";
        case TokenType::TInt8:        return "TInt8";
        case TokenType::TUInt64:      return "TUInt64";
        case TokenType::TUInt32:      return "TUInt32";
        case TokenType::TUInt16:      return "TUInt16";
        case TokenType::TUInt8:       return "TUInt8";
        case TokenType::TFloat64:     return "TFloat64";
        case TokenType::TFloat32:     return "TFloat32";
        case TokenType::TBool:        return "TBool";
        case TokenType::TString:      return "TString";
        case TokenType::TVoid:        return "TVoid";
        case TokenType::TAny:         return "TAny";
        case TokenType::Let:          return "Let";
        case TokenType::Mut:          return "Mut";
        case TokenType::Const:        return "Const";
        case TokenType::If:           return "If";
        case TokenType::Else:         return "Else";
        case TokenType::While:        return "While";
        case TokenType::For:          return "For";
        case TokenType::In:           return "In";
        case TokenType::Return:       return "Return";
        case TokenType::Match:        return "Match";
        case TokenType::Fn:           return "Fn";
        case TokenType::Static:       return "Static";
        case TokenType::Model:        return "Model";
        case TokenType::Union:        return "Union";
        case TokenType::Spawn:        return "Spawn";
        case TokenType::Await:        return "Await";
        case TokenType::Yield:        return "Yield";
        case TokenType::Print:        return "Print";
        case TokenType::PrintErr:     return "PrintErr";
        case TokenType::As:           return "As";
        case TokenType::This:         return "This";
        case TokenType::Plus:         return "Plus";
        case TokenType::Minus:        return "Minus";
        case TokenType::Star:         return "Star";
        case TokenType::Slash:        return "Slash";
        case TokenType::Percent:      return "Percent";
        case TokenType::PlusEqual:    return "PlusEqual";
        case TokenType::MinusEqual:   return "MinusEqual";
        case TokenType::StarEqual:    return "StarEqual";
        case TokenType::SlashEqual:   return "SlashEqual";
        case TokenType::Equal:        return "Equal";
        case TokenType::NotEqual:     return "NotEqual";
        case TokenType::Less:         return "Less";
        case TokenType::Greater:      return "Greater";
        case TokenType::LessEqual:    return "LessEqual";
        case TokenType::GreaterEqual: return "GreaterEqual";
        case TokenType::LogicalAnd:   return "LogicalAnd";
        case TokenType::LogicalOr:    return "LogicalOr";
        case TokenType::LogicalNot:   return "LogicalNot";
        case TokenType::BitAnd:       return "BitAnd";
        case TokenType::Pipe:         return "Pipe";
        case TokenType::BitXor:       return "BitXor";
        case TokenType::BitNot:       return "BitNot";
        case TokenType::BitLShift:    return "BitLShift";
        case TokenType::BitRshift:    return "BitRshift";
        case TokenType::Assign:       return "Assign";
        case TokenType::Arrow:        return "Arrow";
        case TokenType::FatArrow:     return "FatArrow";
        case TokenType::DotDot:       return "DotDot";
        case TokenType::DotDotEq:     return "DotDotEq";
        case TokenType::Dot:          return "Dot";
        case TokenType::Comma:        return "Comma";
        case TokenType::Colon:        return "Colon";
        case TokenType::ColonColon:   return "ColonColon";
        case TokenType::Semicolon:    return "Semicolon";
        case TokenType::Question:     return "Question";
        case TokenType::LeftParen:    return "LeftParen";
        case TokenType::RightParen:   return "RightParen";
        case TokenType::LeftBrace:    return "LeftBrace";
        case TokenType::RightBrace:   return "RightBrace";
        case TokenType::LeftBracket:  return "LeftBracket";
        case TokenType::RightBracket: return "RightBracket";
        case TokenType::Underscore:   return "Underscore";
        case TokenType::Fstring:      return "Fstring";
        case TokenType::Newline:      return "Newline";
        case TokenType::Eof:          return "Eof";
        case TokenType::Invalid:      return "Invalid";
        default: return "Unknown token, damn, Miki?";
    }
}
